# Generated by Django 3.0.3 on 2020-04-26 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alternativeSuccess', '0006_auto_20200426_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='school',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schools', to='alternativeSuccess.School'),
        ),
        migrations.AlterField(
            model_name='school',
            name='programs',
            field=models.ManyToManyField(blank=True, default=None, null=True, related_name='schoolprograms', to='alternativeSuccess.Program'),
        ),
    ]
