# Generated by Django 3.0.3 on 2020-04-26 16:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alternativeSuccess', '0008_program_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='mentor',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='studentsmentor', to=settings.AUTH_USER_MODEL),
        ),
    ]
