# Generated by Django 3.0.3 on 2020-04-27 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alternativeSuccess', '0010_auto_20200426_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='following',
            field=models.ManyToManyField(default=None, related_name='schools_followed', to='alternativeSuccess.School'),
        ),
    ]
